def normalize_text(text: String) -> String:
    var normalized = text.lower()
    normalized = normalized.replace("\r", " ")
    normalized = normalized.replace("\n", " ")
    normalized = normalized.replace("\t", " ")
    normalized = normalized.replace(".", " ")
    normalized = normalized.replace(",", " ")
    normalized = normalized.replace(":", " ")
    normalized = normalized.replace(";", " ")
    normalized = normalized.replace("?", " ")
    normalized = normalized.replace("!", " ")
    normalized = normalized.replace("(", " ")
    normalized = normalized.replace(")", " ")
    normalized = normalized.replace("[", " ")
    normalized = normalized.replace("]", " ")
    normalized = normalized.replace("{", " ")
    normalized = normalized.replace("}", " ")
    normalized = normalized.replace("\"", " ")
    normalized = normalized.replace("'", " ")
    normalized = normalized.replace("-", " ")
    normalized = normalized.replace("/", " ")
    normalized = normalized.replace("\\", " ")
    return normalized
