"""Public Python SDK for Kayak late-interaction programming.

Import from ``kayak`` when writing application or research code in Python.
This package owns the stable late-interaction object model, text encoders,
stores, exact and stage-aware local operations, and explicit backend
selection for the SDK surface.

It is not the hosted engine surface for collections, snapshots, or service
operations. The sibling ``kayak_bridge`` package remains an internal
implementation layer for this monorepo and is not a supported public import
surface.
"""

from kayak_bridge import (
    BackendInfo,
    CandidateGenerator,
    CandidateStageResult,
    LateDocuments,
    LateIndex,
    LateQuery,
    LateQueryBatch,
    LateScores,
    MOJO_EXACT_CPU_BACKEND,
    NUMPY_REFERENCE_BACKEND,
    SearchHit,
    SearchPlan,
    SearchPlanResult,
    SearchStageProfile,
    Stage2ReferenceOperator,
    Stage3VerifierOperator,
    ReferenceScoringSemantics,
    StageArtifactMaterialization,
    available_backends,
    backend_info,
    clause_text_stage3_verifier_operator,
    exact_late_interaction_reference_scoring_semantics,
    document_proxy_candidate_generator,
    document_proxy_search_plan,
    documents,
    exact_full_scan_clause_text_search_plan,
    exact_full_scan_candidate_generator,
    exact_full_scan_search_plan,
    exact_late_interaction_stage2_reference_operator,
    flat_query_dim128,
    generate_candidates,
    hybrid_flat_dim128_index,
    maxsim,
    maxsim_batch,
    none_stage3_verifier_operator,
    noop_topk_stage2_reference_operator,
    packed_index,
    query,
    query_batch,
    search,
    search_batch,
    search_with_plan,
)
from .encoders import (
    CallableLateTextEncoder,
    ColBERTTextEncoder,
    DEFAULT_COLBERT_MODEL_NAME,
    LateTextEncoder,
    open_encoder,
    register_encoder,
)
from .stores import (
    DirectoryLateStore,
    LanceDBLateStore,
    LateStore,
    LateStoreStats,
    MemoryLateStore,
    StoreCapabilities,
    open_store,
    register_store,
)

PUBLIC_API = (
    "BackendInfo",
    "CandidateGenerator",
    "CandidateStageResult",
    "CallableLateTextEncoder",
    "ColBERTTextEncoder",
    "DEFAULT_COLBERT_MODEL_NAME",
    "DirectoryLateStore",
    "LanceDBLateStore",
    "LateDocuments",
    "LateIndex",
    "LateQuery",
    "LateQueryBatch",
    "LateScores",
    "LateStore",
    "LateStoreStats",
    "LateTextEncoder",
    "MemoryLateStore",
    "SearchHit",
    "SearchPlan",
    "SearchPlanResult",
    "SearchStageProfile",
    "Stage2ReferenceOperator",
    "Stage3VerifierOperator",
    "ReferenceScoringSemantics",
    "StageArtifactMaterialization",
    "MOJO_EXACT_CPU_BACKEND",
    "NUMPY_REFERENCE_BACKEND",
    "StoreCapabilities",
    "available_backends",
    "backend_info",
    "clause_text_stage3_verifier_operator",
    "exact_late_interaction_reference_scoring_semantics",
    "document_proxy_candidate_generator",
    "document_proxy_search_plan",
    "documents",
    "exact_full_scan_clause_text_search_plan",
    "exact_full_scan_candidate_generator",
    "exact_full_scan_search_plan",
    "exact_late_interaction_stage2_reference_operator",
    "flat_query_dim128",
    "generate_candidates",
    "hybrid_flat_dim128_index",
    "maxsim",
    "maxsim_batch",
    "none_stage3_verifier_operator",
    "noop_topk_stage2_reference_operator",
    "open_encoder",
    "open_store",
    "packed_index",
    "query",
    "query_batch",
    "register_encoder",
    "register_store",
    "search",
    "search_batch",
    "search_with_plan",
)

__all__ = [
    *PUBLIC_API,
]
